#!/bin/sh
# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2016 Matt Churchyard <churchers@gmail.com>
# SPDX-FileCopyrightText: 2026 Petr Derbyshev <drvpotr@gmail.com>

qemu_qmp(){
    local _name="$1"
    local _command="$2"
    local _socket="${VM_DS_PATH}/${_name}/${_name}.qmp"

    [ -S "${_socket}" ] || \
        util_err "QMP socket not found for ${_name}"

    printf '%s\n' "${_command}" | \
        socat - UNIX-CONNECT:"${_socket}"
}

vm_getpid(){

    local _name="$1"
    local _pidfile="${VM_DS_PATH}/${_name}/${_name}.pid"

    [ -r "${_pidfile}" ] || return 1

    cat "${_pidfile}"
}

# poll until a pid disappears, or a timeout (in seconds) elapses
#
# @private
# @param int _pid pid to watch
# @param int _timeout seconds to wait before giving up (default 90)
# @return 0 if the process exited, 1 if it is still running after the timeout
#
qemu_wait_exit(){
    local _pid="$1"
    local _timeout="${2:-90}"
    local _waited=0

    while kill -0 "${_pid}" 2>/dev/null; do
        [ "${_waited}" -ge "${_timeout}" ] && return 1
        sleep 1
        _waited=$((_waited + 1))
    done

    return 0
}

# 'vm list'
# list virtual machines
#
core_list(){
    local _running_only
    local _name _loader _cpu _our_host
    local _memory _run _vm _auto _num _vnc _pid
    local _state _pcpu _rss _uptime _tags _filter_tag
    local _format="%s^%s^%s^%s^%s^%s^%s^%s^%s\n"

    while getopts rvt: _opt ; do
        case ${_opt} in
            r) _running_only='true' ;;
            t) _filter_tag="${OPTARG}" ;;
            v) VM_OPT_VERBOSE="1" ;;
            *) help_show "list" ;;
        esac
    done

    _our_host=$(hostname)

    vm_running_load

    [ -n "${VM_OPT_VERBOSE}" ] && _format="%s^%s^%s^%s^%s^%s^%s^%5s^%8s^%14s^%s^%s\n";

    # pass everything below here to column(1)
    {
        if [ -n "${VM_OPT_VERBOSE}" ]; then
            printf "${_format}" "NAME" "DATASTORE" "LOADER" "CPU" "MEMORY" "VNC" "AUTO" "%CPU" "RSZ" "UPTIME" "STATE" "TAGS"
        else
            printf "${_format}" "NAME" "DATASTORE" "LOADER" "CPU" "MEMORY" "VNC" "AUTO" "STATE" "TAGS"
        fi

        for _ds in ${VM_DATASTORE_LIST}; do
            datastore_get "${_ds}" || continue

            ls -1 "${VM_DS_PATH}" 2>/dev/null | \
            while read _name; do
                [ ! -e "${VM_DS_PATH}/${_name}/${_name}.conf" ] && continue

                config_load "${VM_DS_PATH}/${_name}/${_name}.conf"
                config_get "_loader" "loader" "none"
                config_get "_cpu" "cpu"
                config_get "_memory" "memory"
                config_get "_tags" "tags" "-"

                # filter guests by tag if specified by -t option
                if [ -n "${_filter_tag}" ]; then
                    printf "%s\n" ${_tags} | grep -qx "${_filter_tag}" || continue
                fi

                # convert tags to comma-separated
                _tags=$(echo ${_tags:--} | tr ' ' ',')

                # defaults
                _vnc="-"
                _pid=""
                _state=""
                _pcpu="-"
                _rss="-"
                _uptime="-"

                # check if the guest is running
                if vm_running_check "_run" "_pid" "${_name}" || \
                    [ -e "${VM_DS_PATH}/${_name}/run.lock" -a "$(head -n1 ${VM_DS_PATH}/${_name}/run.lock 2>/dev/null)" = "${_our_host}" ]; then

                    # if running and graphics, try to get vnc port
                    if config_yesno "graphics"; then
                        _vnc=$(grep ^vnc "${VM_DS_PATH}/${_name}/console" 2>/dev/null |cut -d= -f2)
                        [ -z "${_vnc}" ] && _vnc="-"
                    fi
                fi

                if [ -n "${_pid}" -a -n "${VM_OPT_VERBOSE}" ]; then
                    _state=$(ps -o"%cpu"= -o"rss"= -o"etime"= -p "${_pid}")

                    if [ -n "${_state}" ]; then
                        util_get_part "_pcpu" "${_state}" 1
                        util_get_part "_rss" "${_state}" 2
                        util_get_part "_uptime" "${_state}" 3

                        [ -n "${_rss}" ] && _rss=$(info___bytes_human "${_rss}" 1 2)
                        _uptime=$(echo "${_uptime}" |sed 's/\-/d /')
                    fi
                fi

                _num=1
                _auto="No"

                # find out if we auto-start this vm, and get sequence number
                for _vm in ${vm_list}; do
                    [ "${_vm}" = "${_name}" ] && _auto="Yes [${_num}]"
                    _num=$((_num + 1))
                done

                # if stopped, see if it's locked by another host
                if [ "${_run}" = "Stopped" -a -e "${VM_DS_PATH}/${_name}/run.lock" ]; then
                    _run=$(head -n1 "${VM_DS_PATH}/${_name}/run.lock")
                    _run="Locked (${_run})"
                fi

                if [ -n "${_running_only}" ]; then
                    if [ "${_run}" = "Stopped" -o "${_run}" = "Suspended" ]; then
                        continue
                    fi
                fi

                if [ -n "${VM_OPT_VERBOSE}" ]; then
                    printf "${_format}" "${_name}" "${_ds}" "${_loader}" "${_cpu}" "${_memory}" "${_vnc}" "${_auto}" "${_pcpu}" "${_rss}" "${_uptime}" "${_run}" "${_tags}"
                else
                    printf "${_format}" "${_name}" "${_ds}" "${_loader}" "${_cpu}" "${_memory}" "${_vnc}" "${_auto}" "${_run}" "${_tags}"
                fi
            done
        done
    } | column -ts^
}

# 'vm create'
# create a new virtual machine
#
# @param optional string (-t) _template the template to use (default = default)
# @param optional string (-s) _size guest size (default = 20G)
# @param string _name the name of the guest to create
#
core_create(){
    local _name _opt _size _vmdir _disk _disk_dev _num=0
    local _zfs_opts _disk_size _template="default" _ds="default" _ds_path _img _cpu _memory _uuid
    local _enable_cloud_init _cloud_init_dir _ssh_public_keys _ssh_public_key _ssh_key_file _network_config _mac
    local _user_data_file

    while getopts d:t:s:i:c:m:Ck:n:u: _opt ; do
        case $_opt in
            t) _template=${OPTARG} ;;
            s) _size=${OPTARG} ;;
            d) _ds=${OPTARG} ;;
            c) _cpu=${OPTARG} ;;
            m) _memory=${OPTARG} ;;
            i) _img=${OPTARG} ;;
            k) _ssh_key_file=${OPTARG} ;;
            C) _enable_cloud_init='true' ;;
            n) _network_config=${OPTARG} ;;
            u) _user_data_file=${OPTARG} ;;

            *) help_show "create" ;;
        esac
    done

    shift $((OPTIND - 1))
    _name=$1

    [ -z "${_name}" ] && help_show "create"

    # check guest name
    util_check_name "${_name}" || util_err "invalid virtual machine name - '${_name}'"
    datastore_get_guest "${_name}" && util_err "virtual machine already exists in ${VM_DS_PATH}/${_name}"
    datastore_get "${_ds}" || util_err "unable to load datastore - '${_ds}'"

    [ ! -f "${vm_dir}/.templates/${_template}.conf" ] && \
        util_err "unable to find template ${vm_dir}/.templates/${_template}.conf"

    # we need to get disk0 name and device type from the template
    config_load "${vm_dir}/.templates/${_template}.conf"
    config_get "_disk" "disk0_name"
    config_get "_disk_dev" "disk0_dev"
    config_get "_disk_size" "disk0_size" "20G"
    config_get "_zfs_opts" "zfs_dataset_opts"

    # make sure template has a disk before we start creating anything
    [ -z "${_disk}" ] && util_err "template is missing disk0_name specification"

    # get ssh public key for cloud-init from file
    if [ -n "${_ssh_key_file}" ]; then
      [ -z "${_enable_cloud_init}" ] && util_err "cloud-init is required for injecting public key. Use -C to enable it."
      [ ! -r "${_ssh_key_file}" ] && util_err "can't read file with public key (${_ssh_key_file})"
      _ssh_public_keys="$(sed -e '/^$/d' -e '/^#/d' "${_ssh_key_file}")"
    fi

    # validate user-data file for cloud-init
    if [ -n "${_user_data_file}" ]; then
      [ -z "${_enable_cloud_init}" ] && util_err "cloud-init is required for user-data file. Use -C to enable it."
      [ ! -r "${_user_data_file}" ] && util_err "can't read user-data file (${_user_data_file})"
    fi

    # -u and -k are mutually exclusive
    if [ -n "${_user_data_file}" ] && [ -n "${_ssh_key_file}" ]; then
      util_err "-u and -k are mutually exclusive; use one or the other"
    fi

    # validate network config for cloud-init
    if [ -n "${_network_config}" ]; then
      [ -z "${_enable_cloud_init}" ] && util_err "cloud-init is required for network config. Use -C to enable it."
    fi

    # if we're on zfs, make a new filesystem
    zfs_make_dataset "${VM_DS_ZFS_DATASET}/${_name}" "${_zfs_opts}"

    [ ! -d "${VM_DS_PATH}/${_name}" ] && mkdir "${VM_DS_PATH}/${_name}" >/dev/null 2>&1
    [ ! -d "${VM_DS_PATH}/${_name}" ] && util_err "unable to create virtual machine directory ${VM_DS_PATH}/${_name}"

    cp "${vm_dir}/.templates/${_template}.conf" "${VM_DS_PATH}/${_name}/${_name}.conf"
    [ $? -eq 0 ] || util_err "unable to copy template to virtual machine directory"

    # generate a uuid
    # uuidgen comes from util-linux and isn't installed everywhere; the
    # kernel always provides one. Never write an empty uuid= to the config.
    _uuid=$(uuidgen 2>/dev/null)
    [ -z "${_uuid}" ] && _uuid=$(cat /proc/sys/kernel/random/uuid 2>/dev/null)
    [ -z "${_uuid}" ] && util_err "unable to generate a uuid for ${_name}"
    config_set "${_name}" "uuid" ${_uuid}

    # get any zvol options
    config_get "_zfs_opts" "zfs_zvol_opts"

    # generate mac address - it's saved in _mac variable
    vm_generate_static_mac

    # Optional overrides
    [ -n "${_cpu}" ] && config_set "${_name}" "cpu" "${_cpu}"
    [ -n "${_memory}" ] && config_set "${_name}" "memory" "${_memory}"
    # use cmd line size for disk 0 if specified
    [ -n "${_size}" ] && _disk_size="${_size}"

    # create each disk
    while [ -n "${_disk}" ]; do
        case "${_disk_dev}" in
            zvol)
                zfs_make_zvol "${VM_DS_ZFS_DATASET}/${_name}/${_disk}" "${_disk_size}" "0" "${_zfs_opts}"
                [ $_num -eq 0 ] && [ ! -z "$_img" ] && core_write_img "/dev/zvol/${VM_DS_ZFS_DATASET}/${_name}/${_disk}" "${_img}" "${_disk_dev}" "${_disk_size}"
                ;;
            sparse-zvol)
                zfs_make_zvol "${VM_DS_ZFS_DATASET}/${_name}/${_disk}" "${_disk_size}" "1" "${_zfs_opts}"
                [ $_num -eq 0 ] && [ ! -z "$_img" ] && core_write_img "/dev/zvol/${VM_DS_ZFS_DATASET}/${_name}/${_disk}" "${_img}" "${_disk_dev}" "${_disk_size}"
                ;;
            custom)
                ;;
            iscsi)
                ;;
            *)
                truncate -s "${_disk_size}" "${VM_DS_PATH}/${_name}/${_disk}"
                [ $? -eq 0 ] || util_err "failed to create sparse file for disk image"

                # make sure only owner can read the disk image
                chmod 600 "${VM_DS_PATH}/${_name}/${_disk}"
                [ $_num -eq 0 ] && [ ! -z "$_img" ] && core_write_img "${VM_DS_PATH}/${_name}/${_disk}" "${_img}" "file" "${_disk_size}"
                ;;
        esac

        # scrap size option from guest template
        # disk size has already been consumed when the disk was created
        config_unset "${_name}" "disk${_num}_size"

        # look for another disk
        _num=$((_num + 1))
        config_get "_disk" "disk${_num}_name"
        config_get "_disk_dev" "disk${_num}_dev"
        config_get "_disk_size" "disk${_num}_size" "20G"
    done

    if [ -n "${_enable_cloud_init}" ]; then
        core_create_cloud_init
    fi

    exit 0
}

core_create_cloud_init(){
    local _cloud_init_dir _hostname
    local _network_config_interface _network_config_ipaddress _network_config_gateway4 \
          _network_config_gateway6 _network_config_nameservers _network_config_searchdomains \
          _network_config_hostname

    # create disk with metadata for cloud-init
    _cloud_init_dir="${VM_DS_PATH}/${_name}/.cloud-init"
    # Use VM's name as a hostname by default
    _hostname="${_name}"

    mkdir -p "${_cloud_init_dir}"

    if [ -n "${_network_config}" ]; then
        core_parse_netconfig "${_network_config}"
        core_compile_network_config > "${_cloud_init_dir}/network-config"

        # Override default hostname when network config is passed to cloud-init
        if [ ! -z "${_network_config_hostname}" ]; then
                _hostname="${_network_config_hostname}"
        fi
    fi

    cat << EOF > "${_cloud_init_dir}/meta-data"
instance-id: ${_uuid}
local-hostname: ${_hostname}
EOF

    # create user-data: use provided file or generate default
    if [ -n "${_user_data_file}" ]; then
        cp "${_user_data_file}" "${_cloud_init_dir}/user-data"
    else
        cat << EOF > "${_cloud_init_dir}/user-data"
#cloud-config
resize_rootfs: True
manage_etc_hosts: localhost
EOF

        if [ -n "${_ssh_public_keys}" ]; then
            cat << EOF >> "${_cloud_init_dir}/user-data"
ssh_authorized_keys:
EOF
            echo "${_ssh_public_keys}" | while read -r _ssh_public_key; do
                cat << EOF >> "${_cloud_init_dir}/user-data"
  - ${_ssh_public_key}
EOF
            done
        fi
    fi

    config_set "${_name}" "disk${_num}_type" "ahci-cd"
    config_set "${_name}" "disk${_num}_name" "seed.iso"
    config_set "${_name}" "disk${_num}_dev" "file"
}


# parse cloud-init netconfig string passed via `vm create -C -n [netconfig]`
#
# @private
# @param string netconfig
#
core_parse_netconfig(){
    local _network_config

    _network_config="$1"

    _network_config_interface="$(echo "${_network_config}" | \
        grep -oE 'interface=[^;]*' | sed 's/^interface=//')";
    _network_config_ipaddress="$(echo "${_network_config}" | \
        grep -oE 'ip=[^;]*' | sed 's/^ip=//')"
    _network_config_gateway4="$(echo "${_network_config}" | \
        grep -oE 'gateway4=[^;]*' | sed 's/^gateway4=//')"
    _network_config_gateway6="$(echo "${_network_config}" | \
        grep -oE 'gateway6=[^;]*' | sed 's/^gateway6=//')"
    _network_config_nameservers="$(echo "${_network_config}" | \
        grep -oE 'nameservers=[^;]*' | sed 's/^nameservers=//')"
    _network_config_searchdomains="$(echo "${_network_config}" | \
        grep -oE 'searchdomains=[^;]*' | sed 's/^searchdomains=//')"
    _network_config_hostname="$(echo "${_network_config}" | \
        grep -oE 'hostname=[^;]*' | sed 's/^hostname=//')"

}

# compile cloud-init network-config
#
# @private
#
core_compile_network_config(){
    local _addr _ipv4_found ipv6_found
    local _tmpfile=$(mktemp)

    cat << EOF >> "${_tmpfile}"
version: 2
ethernets:
  id0:
EOF

    echo "    set-name: ${_network_config_interface:-eth0}" >> ${_tmpfile}
    echo "    match:" >> ${_tmpfile}
    echo "      macaddress: ${_mac}" >> ${_tmpfile}

    # IP addresses
    if [ ! -z "${_network_config_ipaddress}" ]; then
        OLDIFS=$IFS
        IFS=,
        for _addr in ${_network_config_ipaddress}; do
            case "${_addr}" in
                *:*)
                    _ipv6_found="1"
                    ;;
                *.*)
                    _ipv4_found="1"
                    ;;

            esac
        done
        IFS=$OLDIFS
        echo "    addresses: [${_network_config_ipaddress}]" >> ${_tmpfile}
    fi

    # use DHCP if no IPv4 address specified
    if [ -z "${_ipv4_found}" ]; then
        echo "    dhcp4: true" >> ${_tmpfile}
    fi

    # use DHCP and RA if no IPv6 specified
    if [ -z "${_ipv6_found}" ]; then
        echo "    dhcp6: true"  >> ${_tmpfile}
        echo "    accept-ra: true"  >> ${_tmpfile}
    fi

    # nameservers & searchdomains
    if [ -n "${_network_config_serachdomains}" -o -n "${_network_config_nameservers}" ]; then
        echo "    nameservers:" >> ${_tmpfile}

        if [ -n "${_network_config_nameservers}" ]; then
            echo "      addresses: [${_network_config_nameservers}]" >> ${_tmpfile}
        fi

        if [ -n "${_searchdomains}" ]; then
            echo "      search: [${_searchdomains}]" >> ${_tmpfile}
        fi
    fi

    # gateway
    if [ -n "${_network_config_gateway4}" -o -n "${_network_config_gateway6}" ]; then
        echo "    routes:" >> ${_tmpfile}

        if [ -n "${_network_config_gateway4}" ]; then
            echo "      - to: 0.0.0.0/0" >> ${_tmpfile}
            echo "        via: ${_network_config_gateway4}" >> ${_tmpfile}
        fi

        if [ -n "${_network_config_gateway6}" ]; then
            echo "      - to: _/0" >> ${_tmpfile}
            echo "        via: ${_network_config_gateway6}" >> ${_tmpfile}
        fi
    fi


    cat "${_tmpfile}"
    rm -f -- "${_tmpfile}"
}

# write cloud image to disk image
#
# @private
# @param string _disk_dev device to write image to
# @param string _img the img file in $vm_dir/.img to use
#
core_write_img(){
    local _disk_dev _img _imgpath

    cmd_parse_args "$@"
    shift $?
    _disk_dev="${1}"
    _img="$2"
    _disk_type="$3"
    _disk_size="$4"
    timeout=30
    i=0

    # wait a few seconds for newly created zvol device to appear
    while [ $i -lt $timeout ]; do
        if [ ! -r "${_disk_dev}" ]; then
            sleep 1
            i=$(($i+1))
        else
            break
        fi
    done

    # just run start with an iso
    datastore_img_find "_imgpath" "${_img}" || util_err "unable to locate img file - '${_img}'"
    qemu-img dd -O raw if="${_imgpath}" of="${_disk_dev}" bs=1M
    if [ $? -ne 0 ]; then
        util_err "failed to write img file with qemu-img"
    fi

    # if disk type is file then we need to resize it
    if [ "${_disk_type}" = "file" ]; then
        qemu-img resize -q -f raw "${_disk_dev}" "${_disk_size}"
        if [ $? -ne 0 ]; then
            util_err "failed to resize img file with qemu-img"
        fi
    fi
}

# 'vm add'
# add a device to an existing guest
#
# @param string (-d) _device=network|disk the type of device to add
# @param string (-t) _type for disk, the type of disk - file|zvol|sparse-zvol
# @param string (-s) _sopt for disk the size, for network the virtual switch name
# @param string _name name of the guest
#
core_add(){
    local _name _device _type _sopt _opt

    while getopts d:t:s: _opt; do
        case $_opt in
            d) _device=${OPTARG} ;;
            t) _type=${OPTARG} ;;
            s) _sopt=${OPTARG} ;;
            *) help_show "add";;
        esac
    done

    shift $((OPTIND - 1))
    _name="$1"

    # check guest
    [ -z "${_name}" ] && help_show "add"
    datastore_get_guest "${_name}" || "${_name} does not appear to be a valid virtual machine"

    case "${_device}" in
        disk)    core_add_disk "${_name}" "${_type}" "${_sopt}" ;;
        network) core_add_network "${_name}" "${_sopt}" ;;
        *)       util_err "device must be one of the following: disk network" ;;
    esac
}

# add a disk to guest
# this creates the disk image or zvol and updates configuration file
# we use the same emulation as the existing disk(s)
#
# @private
# @param string _name name of the guest
# @param string _device type of device file|zvol|sparse-zvol
# @param string _size size of the disk to create
#
core_add_disk(){
    local _name="$1"
    local _device="$2"
    local _size="$3"
    local _num=0 _curr _diskname _emulation _zfs_opts

    : ${_device:=file}

    [ -z "${_size}" ] && help_show "add"

    # get the last existing disk
    config_load "${VM_DS_PATH}/${_name}/${_name}.conf"
    config_get "_zfs_opts" "zfs_zvol_opts"

    while true; do
        config_get "_curr" "disk${_num}_name"
        [ -z "${_curr}" ] && break
        config_get "_emulation" "disk${_num}_type"
        _num=$((_num + 1))
    done

    [ -z "${_emulation}" ] && util_err "failed to get emulation type of the existing guest disks"

    # create the disk first, then update config if no problems
    case "${_device}" in
        zvol)
            zfs_make_zvol "${VM_DS_ZFS_DATASET}/${_name}/disk${_num}" "${_size}" "0" "${_zfs_opts}"
            _diskname="disk${_num}"
            ;;
        sparse-zvol)
            zfs_make_zvol "${VM_DS_ZFS_DATASET}/${_name}/disk${_num}" "${_size}" "1" "${_zfs_opts}"
            _diskname="disk${_num}"
            ;;
        file)
            truncate -s "${_size}" "${VM_DS_PATH}/${_name}/disk${_num}.img"
            [ $? -eq 0 ] || util_err "failed to create sparse file for disk image"
            _diskname="disk${_num}.img"
            ;;
        *)
            util_err "device type must be one of the following: zvol sparse-zvol file"
            ;;
    esac

    # update configuration
    config_set "${_name}" "disk${_num}_name" "${_diskname}"
    config_set "${_name}" "disk${_num}_type" "${_emulation}" "1"
    config_set "${_name}" "disk${_num}_dev" "${_device}" "1"
    [ $? -eq 0 ] || util_err "disk image created but errors while updating guest configuration"
}

# add network interface to guest
#
# @private
# @param string _name name of the guest
# @param string _switch the switch name for this interface
#
core_add_network(){
    local _name="$1"
    local _switch="$2"
    local _num=0 _curr _emulation

    [ -z "${_switch}" ] && help_show "add"

    config_load "${VM_DS_PATH}/${_name}/${_name}.conf"

    while true; do
        _emulation="${_curr}"
        config_get "_curr" "network${_num}_type"
        [ -z "${_curr}" ] && break
        _num=$((_num + 1))
    done

    # handle no existing network
    : ${_emulation:=virtio-net}

    # update configuration
    config_set "${_name}" "network${_num}_type" "${_emulation}"
    config_set "${_name}" "network${_num}_switch" "${_switch}" "1"
    [ $? -eq 0 ] || util_err "errors encountered while updating guest configuration"
}

# 'vm install'
# install os to a virtual machine
#
# @param string _name the guest to install to
# @param string _iso the iso file in $vm_dir/.iso to use
#
core_install(){
    local _name _iso _fulliso

    cmd_parse_args "$@"
    shift $?
    _name="$1"
    _iso="$2"

    [ -z "${_name}" -o -z "${_iso}" ] && help_show "install"

    # just run start with an iso
    datastore_iso_find "_fulliso" "${_iso}" || util_err "unable to locate iso file - '${_iso}'"
    core___start "${_name}" "${_fulliso}"
}

# 'vm startall'
# start all virtual machines listed in rc.conf:$vm_list
#
core_startall(){
    [ -z "${vm_list}" ] && exit
    core_start ${vm_list}
}

# 'vm stopall'
# stop all bhyve instances
# note this will also stop instances not started by vm-bhyve
#
# 'vm stopall'
#
# stop all running virtual machines
#
core_stopall(){
    local _running
    local _stop_parallel
    local _stop_list
    local _list_rev
    local _curr
    local _done

    cmd_parse_args "$@"
    : ${vm_delay:=2}

    #
    # Get all running VM names.
    #
    # Linux/QEMU: qemu-system-* processes carry "-name <vm-name>" on
    # their command line, so the guest name can be recovered straight
    # from ps(1). This also catches instances not started by this
    # tool, mirroring the original bhyve behaviour.
    #
    _running=$(
        ps -eo args= |
        sed -n 's/.*-name[[:space:]]\+\([^,[:space:]]*\).*/\1/p' |
        sort -u |
        tr '\n' ' '
    )

    [ -z "${_running}" ] && return 0

    #
    # If we have an autostart list and this isn't a forced shutdown,
    # stop VMs in reverse startup order.
    #
    if [ -z "${VM_OPT_FORCE}" -a -n "${vm_list}" ]; then

        #
        # Reverse vm_list.
        #
        for _curr in ${vm_list}; do
            _list_rev="${_curr} ${_list_rev}"
        done

        #
        # Add running autostart VMs to ordered stop list.
        #
        for _curr in ${_list_rev}; do
            echo "${_running}" | grep -F -qw "${_curr}" && \
                _stop_list="${_stop_list}${_stop_list:+ }${_curr}"
        done

        #
        # Find running VMs which aren't in the ordered list.
        # These can be stopped in parallel.
        #
        for _curr in ${_running}; do
            echo "${_stop_list}" | grep -F -qw "${_curr}" || \
                _stop_parallel="${_stop_parallel}${_stop_parallel:+ }${_curr}"
        done

    else
        #
        # No ordered shutdown or force mode:
        # stop everything in parallel.
        #
        _stop_parallel="${_running}"
    fi

    echo "Beginning shutdown process"

    #
    # Stop unordered VMs in parallel - each one gets its own graceful
    # ACPI powerdown (with SIGTERM/SIGKILL escalation) via
    # core___stop_one, running in the background.
    #
    if [ -n "${_stop_parallel}" ]; then
        echo "  * parallel shutdown of non-ordered guests: ${_stop_parallel}"

        for _curr in ${_stop_parallel}; do
            core___stop_one "${_curr}" &
        done

        wait
    fi

    #
    # Stop ordered VMs one by one.
    #
    if [ -n "${_stop_list}" ]; then
        for _curr in ${_stop_list}; do
            [ -n "${_done}" ] && echo "  * waiting ${vm_delay} second(s)" && sleep "${vm_delay}"
            echo "  * stopping ${_curr}"
            core___stop_one "${_curr}"
            _done="1"
        done
    fi

    echo ""
}
# 'vm suspendall'
#
# suspend all bhyve instances
#
# Unlike stopall, this will only suspend instances started by vm-bhyve,
# as it cannot determine where to save the state file for instances
# started by other tools.
#
core_suspendall()
{
    local _stop_parallel _stop_list _running _list_rev _curr
    local _ds _n _p

    cmd_parse_args "$@"
    : ${vm_delay:=2}

    #
    # Linux/QEMU: unlike stopall, we can only suspend guests we started
    # ourselves - that's the only way we know the pid to talk to over
    # QMP and where to write the .save state. So "running" here means
    # "has a live pid file", checked across every guest in every
    # datastore.
    #
    _running=$(
        for _ds in ${VM_DATASTORE_LIST}; do
            datastore_get "${_ds}" || continue
            ls -1 "${VM_DS_PATH}" 2>/dev/null
        done | sort -u | while read -r _n; do
            _p=$(vm_getpid "${_n}")
            [ -n "${_p}" ] && kill -0 "${_p}" 2>/dev/null && echo "${_n}"
        done | tr '\n' ' '
    )

    [ -z "${_running}" ] && return 0

    # do we have any guests to stop in order
    if [ -z "${VM_OPT_FORCE}" -a -n "${vm_list}" ]; then
        # reverse the configured start order
        for _curr in ${vm_list}; do
            _list_rev="${_curr} ${_list_rev}"
        done

        # go through each autostart guest
        # if running add to stop list.
        # we are searching in reverse start order, so should get an ordered shutdown
        for _curr in ${_list_rev}; do
            echo "${_running}" | grep -F -qw "${_curr}" && \
                _stop_list="${_stop_list}${_stop_list:+ }${_curr}"
        done

        # look for anything running that isn't in the ordered stop list
        for _curr in ${_running}; do
            echo "${_stop_list}" | grep -F -qw "${_curr}" || \
                _stop_parallel="${_stop_parallel}${_stop_parallel:+ }${_curr}"
        done
    else
        # nothing ordered, or a force suspend
        # just do everything at once
        _stop_parallel="${_running}"
    fi

    echo "Beginning shutdown process (suspend)"

    # suspending non-ordered guests
    if [ -n "${_stop_parallel}" ]; then
        echo "  * parallel suspend of non-ordered guests: ${_stop_parallel}"
        for _curr in ${_stop_parallel}; do
            echo "  * suspending ${_curr}"
            core_suspend "${_curr}" >/dev/null 2>&1
        done
    fi

    # suspending ordered guests
    if [ -n "${_stop_list}" ]; then
        for _curr in ${_stop_list}; do
            echo "  * waiting ${vm_delay} second(s)" && sleep ${vm_delay}
            echo "  * suspending ${_curr}"
            core_suspend "${_curr}" >/dev/null 2>&1
        done
    fi

    echo ""
}

# 'vm start'
# start a virtual machine
#
# @param string[multiple] _name the name of the guest(s) to start
#
core_start(){
    local _name
    local _done
    local _rc _rcsum=0

    cmd_parse_args "$@"
    shift $?
    _name="$1"

    [ -z "${_name}" ] && help_show "start"
    : ${vm_delay:=2}

    # disable foreground/interactive if we're starting more than one
    if [ $# -ge 2 ]; then
        VM_OPT_FOREGROUND=""
        VM_OPT_INTERACTIVE=""
    fi

    while [ -n "${_name}" ]; do
        [ -n "${_done}" ] && echo "Waiting ${vm_delay} second(s)" && sleep ${vm_delay}
        core___start "${_name}"

        _rc=$?
        if [ ${_rc} -ne 0 ]; then
            _rcsum=$((${_rcsum} + ${_rc}))
        fi
        shift

        _name="$1"
        _done="1"
    done

    # returns the number of VMs that failed to start
    return ${_rcsum}
}

# actually start a virtual machine
#
# @param string _name the name of the guest to start
# @param optional string _iso iso file is this is an install (can only be provided through 'vm install' command)
#
core___start(){
    local _name="$1"
    local _iso="$2"
    local _cpu _memory _disk _guest _loader _console
    local _tmux_cmd _tmux_name _util _uefi

    [ -z "${_name}" ] && util_usage

    echo "Starting ${_name}"

    # try to find guest
    if ! datastore_get_guest "${_name}"; then
        echo "  ! ${_name} does not seem to be a valid virtual machine"
        return 1
    fi

    echo "  * found guest in ${VM_DS_PATH}/${_name}"

    # confirm we aren't running
    if ! vm_confirm_stopped "${_name}" "1" >/dev/null 2>&1; then
        echo "  ! guest appears to be running already"
        return 1
    fi

    # check basic settings before going into background mode
    config_load "${VM_DS_PATH}/${_name}/${_name}.conf"
    config_get "_cpu" "cpu"
    config_get "_memory" "memory"
    config_get "_loader" "loader"

    # check minimum configuration
    if [ -z "${_cpu}" -o -z "${_memory}" ]; then
        echo "  ! incomplete virtual machine configuration"
        return 1
    fi

    # check for tmux
    config_core_get "_console" "console" "stdio"
    _tmux_cmd=$(which tmux)

    if [ "${_console}" = "tmux" -a -z "${_tmux_cmd}" ]; then
        echo "  ! tmux support enabled but misc/tmux not found"
        return 1
    fi

    if util_check_bhyve_suspend >/dev/null 2>&1 && vm_has_saved_state "${_name}"; then
        echo "  * found saved vm state, resuming..."
    else
        echo "  * booting..."
    fi


    # run background process to actually start bhyve
    # this will run as long as vm is running, including restarting bhyve after guest reboot
    if [ -n "${VM_OPT_FOREGROUND}" ]; then
        $0 _run -f "${_name}" "${_iso}"
    elif [ "${_console}" = "tmux" ]; then
        # can't have dots in tmux session :( (looks like it may use . to separate window.pane)
        # use ~ which we don't normally allow
        _tmux_name=$(echo "${_name}" | tr "." "~")

        # start session and connect if in interactive mode
        if [ -n "${VM_OPT_INTERACTIVE}" ]; then
            ${_tmux_cmd} new -s "${_tmux_name}" $0 _run -tf "${_name}" "${_iso}"
        else
            ${_tmux_cmd} new -ds "${_tmux_name}" $0 _run -tf "${_name}" "${_iso}"
        fi
    elif [ -n "${VM_OPT_INTERACTIVE}" ]; then
        # interactive && console != tmux
        # connect to the console using cu if global console setting not set to tmux
        $0 _run "${_name}" "${_iso}" >/dev/null 2>&1 &
        core_console -w "${_name}"
    else
        $0 _run "${_name}" "${_iso}" >/dev/null 2>&1 &
    fi
}

# 'vm restart'
# restart a guest
# all we do is create a "restart" file which vm-run looks for
#
# @param string _name name of the guest to restart
#
core_restart(){
    local _name="$1"

    datastore_get_guest "${_name}" || util_err "unable to locate specified guest"
    echo "Setting guest restart flag"
    touch "${VM_DS_PATH}/${_name}/restart" >/dev/null 2>&1
    core_stop "${_name}"
}

# 'vm stop'
# send a kill signal to the specified guest
#
# @param string[multiple] _name name of the guest to stop
#
core_stop(){
    local _name="$1"
    [ -z "${_name}" ] && help_show "stop"

    while [ -n "${_name}" ]; do
        core___stop_one "${_name}"
        shift
        _name="$1"
    done
}

# gracefully stop a single guest: ACPI powerdown via QMP (equivalent to
# bhyve's SIGTERM-triggered ACPI shutdown), wait for it to exit on its
# own, and only escalate to SIGTERM/SIGKILL if it doesn't within
# ${vm_stop_timeout} seconds. Used by both 'vm stop' and 'vm stopall'.
#
# @private
# @param string _name name of the guest to stop
#
core___stop_one(){
    local _name="$1"
    local _pid

    _pid=$(vm_getpid "${_name}")

    if [ -z "${_pid}" ] || ! kill -0 "${_pid}" 2>/dev/null; then
        util_warn "${_name} doesn't appear to be a running virtual machine"
        return 1
    fi

    : ${vm_stop_timeout:=90}

    echo "Sending ACPI shutdown to ${_name}"

    if [ -S "${VM_DS_PATH}/${_name}/${_name}.qmp" ]; then
        qemu_qmp "${_name}" '{"execute":"system_powerdown"}' >/dev/null 2>&1
    else
        # no QMP socket available - fall back to a plain SIGTERM
        kill -TERM "${_pid}" >/dev/null 2>&1
    fi

    # give the guest OS a chance to shut down cleanly on its own
    if ! qemu_wait_exit "${_pid}" "${vm_stop_timeout}"; then
        util_warn "${_name} did not shut down within ${vm_stop_timeout}s, forcing stop"
        kill -TERM "${_pid}" >/dev/null 2>&1
        qemu_wait_exit "${_pid}" 5 || kill -KILL "${_pid}" >/dev/null 2>&1
    fi

    # remove saved vm state after normal shutdown
    core_discard -f "${_name}" >/dev/null 2>&1
}

core_suspend(){
    local _name="$1"
    [ -z "${_name}" ] && help_show "suspend"
    datastore_get_guest "${_name}" || \
        util_err "${_name} doesn't appear to be a valid virtual machine"
    vm_confirm_running "${_name}" || \
        util_err "${_name} doesn't appear to be a running virtual machine"
    echo "Suspending ${_name}"
    hostname > "${VM_DS_PATH}/${_name}/suspending.lock"
    qemu_qmp "${_name}" \
        "{\"execute\":\"migrate\",\"arguments\":{\"uri\":\"file:${VM_DS_PATH}/${_name}/${_name}.save\"}}"
}



# 'vm reset'
# force reset
#
# @param string _name name of the guest
#
core_reset(){
    local _name
    cmd_parse_args "$@"
    shift $?
    _name="$1"
    [ -z "${_name}" ] && help_show "reset"
    vm_confirm_running "${_name}" || \
        util_err "${_name} doesn't appear to be a running virtual machine"

    if [ -z "${VM_OPT_FORCE}" ]; then
        util_confirm "Are you sure you want to forcefully reset this virtual machine" || exit 0
    fi
    qemu_qmp "${_name}" '{"execute":"system_reset"}'
}

# 'vm poweroff'
# force poweroff
#
# @param string _name name of the guest
#
core_poweroff(){
    local _name
    cmd_parse_args "$@"
    shift $?
    _name="$1"
    [ -z "${_name}" ] && help_show "poweroff"
    vm_confirm_running "${_name}" || \
        util_err "${_name} doesn't appear to be a running virtual machine"
    if [ -z "${VM_OPT_FORCE}" ]; then
        util_confirm "Are you sure you want to forcefully poweroff this virtual machine" || exit 0
    fi
    qemu_qmp "${_name}" '{"execute":"quit"}'
    # remove saved vm state on forceful poweroff
    core_discard -f "${_name}"
}

# 'vm destroy'
# completely remove a guest
#
# @param string _name name of the guest
#
core_destroy(){
    local _name

    cmd_parse_args "$@"
    shift $?
    _name="$1"

    [ -z "${_name}" ] && help_show "destroy"

    # trying to remove a snapshot?
    echo "${_name}" | grep -qs "@"

    if [ $? -eq 0 ]; then
        zfs_remove_snapshot "${_name}"
        exit $?
    fi

    # make sure it's stopped!
    datastore_get_guest "${_name}" || util_err "${_name} doesn't appear to be a valid virtual machine"
    vm_confirm_stopped "${_name}" || exit 1

    if [ -z "${VM_OPT_FORCE}" ]; then
        util_confirm "Are you sure you want to completely remove this virtual machine" || exit 0
    fi

    [ -n "${VM_DS_ZFS_DATASET}" ] && zfs_destroy_dataset "${VM_DS_ZFS_DATASET:?}/${_name:?}"
    [ -e "${VM_DS_PATH}/${_name}" ] && rm -R "${VM_DS_PATH:?}/${_name:?}"

    exit 0
}

# 'vm discard'
# discard the saved state of a guest
#
# @param string _name name of the guest
#
core_discard(){
    local _name _rc=0

    cmd_parse_args "$@"
    shift $?
    _name="$1"

    [ -z "${_name}" ] && help_show "discard"

    # core_discard only accepts one target guest
    [ ! -z "$2" ] && help_show "discard"

    datastore_get_guest "${_name}" || util_err "${_name} doesn't appear to be a valid virtual machine"

    if [ -z "${VM_OPT_FORCE}" ]; then
        util_confirm "Are you sure you want to remove the saved state of this virtual machine" || exit 0
    fi

    if ! vm_has_saved_state "${_name}"; then
        if [ -z "${VM_OPT_FORCE}" ]; then
            util_err "no saved state exists for ${_name}"
        else
            # When VM_OPT_FORCE is set, do not error if no saved state exists
            return 0
        fi
    fi

    # remove vm state file
    find "${VM_DS_PATH}/${_name}" -name "${_name}.save*" -type f -delete

    exit $?
}

# 'vm rename'
# rename an existing guest
#
# @param string _old the existing guest name
# @param string _new the new guest name
#
core_rename(){
    local _old="$1"
    local _new="$2"
    local _mv_failed

    [ -z "${_old}" -o -z "${_new}" ] && help_show "rename"
    util_check_name "${_new}" || util_err "invalid virtual machine name - '${_name}'"

    datastore_get_guest "${_new}" && util_err "directory ${VM_DS_PATH}/${_new} already exists"
    datastore_get_guest "${_old}" || util_err "${_old} doesn't appear to be a valid virtual machine"

    # confirm guest stopped
    vm_confirm_stopped "${_old}" || exit 1

    # rename zfs dataset
    zfs_rename_dataset "${_old}" "${_new}"

    # rename folder if it still exists (shouldn't if zfs mode and rename worked)
    if [ -d "${VM_DS_PATH}/${_old}" ]; then
        mv "${VM_DS_PATH}/${_old}" "${VM_DS_PATH}/${_new}" >/dev/null 2>&1
        [ $? -eq 0 ] || util_err "failed to rename guest directory"
    fi

    # rename config file
    mv "${VM_DS_PATH}/${_new}/${_old}.conf" "${VM_DS_PATH}/${_new}/${_new}.conf" >/dev/null 2>&1
    [ $? -eq 0 ] || util_err "changed guest directory but failed to rename configuration file"

    # rename saved vm state file
    _mv_failed=0
    (
        cd "${VM_DS_PATH}/${_new}" || exit 1
        find . -type f -depth 1 -name "${_old}.save*" | while read -r oldf; do
            newf="$(echo "${oldf}" | sed "s|${_old}|${_new}|" )"
            echo mv "${oldf} ${newf}" || _mv_failed=1
        done
    )
    [ "${_mv_failed}" -eq 0 ] || util_err "changed guest directory but failed to rename saved vm state file"
}

# 'vm console'
# connect to the console (nmdm) of the specified guest
# we store the nmdm for com1 & com2 in $vm_dir/{guest}/console
# if no port is specified, we use the first one that is specified in the configuration file
# so if comports="com2 com1", it will connect to com2
# the boot loader always using the nmdm device of the first com port listed
#
# @param string _name name of the guest
# @param string _port the port to connect to (default = first in configuration)
#
core_console(){
    local _name _port
    local _console _tmux _tmux_cmd _wait_for_vm _pid

    while getopts w _opt ; do
        case $_opt in
            w) _wait_for_vm="1" ;;
            *) help_show "console" ;;
        esac
    done

    shift $((OPTIND - 1))

    _name="$1"
    _port="$2"

    [ -z "${_name}" ] && help_show "console"

    datastore_get_guest "${_name}" || util_err "${_name} doesn't appear to be a valid virtual machine"

    if [ -n "${_wait_for_vm}" ]; then
        echo "Waiting for ${_name} to start..."
        # wait for the pid file to appear and the process to be alive
        sleep 0.05
        while true; do
            _pid=$(vm_getpid "${_name}")
            [ -n "${_pid}" ] && kill -0 "${_pid}" 2>/dev/null && break
            sleep 1
        done
    else
        _pid=$(vm_getpid "${_name}")
        if [ -z "${_pid}" ] || ! kill -0 "${_pid}" 2>/dev/null; then
            util_err "${_name} doesn't appear to be a running virtual machine"
        fi
    fi

    if [ -e "${VM_DS_PATH}/${_name}/console" ]; then

        # did user specify a com port?
        # if not, get first in the file (the first will also be the console used for loader)
        if [ -n "${_port}" ]; then
            _console=$(grep "${_port}=" "${VM_DS_PATH}/${_name}/console" | cut -d= -f2)
        else
            _console=$(head -n 1 "${VM_DS_PATH}/${_name}/console" | grep "^com" | cut -d= -f2)
        fi
    fi

    # is this a tmux console?
    if [ "${_console%%/*}" = "tmux" ]; then
        _tmux_cmd=$(which tmux)

        if [ -n "${_tmux_cmd}" ]; then
            _tmux=$("${_tmux_cmd}" ls |grep "^${_name}:")

            if [ -n "${_tmux}" ]; then
                ${_tmux_cmd} attach -t ${_console##*/}
                exit
            fi
        fi
    fi

    [ -z "${_console}" ] && util_err "unable to locate console device for this virtual machine"
    socat -,raw,echo=0 UNIX-CONNECT:"${_console}"
}

# 'vm configure'
# configure a machine (edit the configuration file)
#
# @param string _name name of the guest
#
core_configure(){
    local _name="$1"
    local _target="$2"

    [ -z "${_name}" ] && help_show "configure"
    [ -z "${EDITOR}" ] && EDITOR="vi"

    datastore_get_guest "${_name}" || \
        util_err "cannot locate configuration file for virtual machine: ${_name}"

    case "$_target" in
        meta-data|network-config|user-data)
            [ -d "${VM_DS_PATH}/${_name}/.cloud-init" ] || \
                util_err "cloud-init is not enabled for this guest"
            if [ -e "${VM_DS_PATH}/${_name}/seed.iso" ]; then
                util_confirm "cloud-init has run already. changes won't take effect. edit anyway?" || exit 0
            fi

            $EDITOR "${VM_DS_PATH}/${_name}/.cloud-init/${_target}"
            ;;
        "")
            $EDITOR "${VM_DS_PATH}/${_name}/${_name}.conf"
            ;;
        *)
            help_show "configure"
            ;;
    esac
}

# 'vm iso'
# list iso images or get a new one
#
# @param string _url if specified, the url will be fetch'ed into $vm_dir/.iso
#
core_iso(){
    local _url _ds="default" _filename
    local _fetch_opts

    while getopts 46d:u _opt ; do
        case $_opt in
            4) _fetch_opts="${_fetch_opts} -4" ;;
            6) _fetch_opts="${_fetch_opts} -6" ;;
            d) _ds=${OPTARG} ;;
            *) help_show "iso" ;;
        esac
    done

    shift $((OPTIND - 1))
    _url=$1

    if [ -n "${_url}" ]; then
        datastore_get_iso "${_ds}" || util_err "unable to locate path for datastore '${_ds}'"
        # converted from Fetch to Curl
	_filename=$(basename "${_url}")
	case "${_fetch_opts}" in
	    *"-4"*)
        	_curl_opts="-4"
        	;;
	    *"-6"*)
        	_curl_opts="-6"
        	;;
	    *)
        	_curl_opts=""
        	;;
	esac
	curl -L ${_curl_opts} -o "${VM_DS_PATH}/${_filename}" "${_url}" || \
	    util_err "failed to download ISO image"

	core_decompress "${VM_DS_PATH}/${_filename}"
    else
        datastore_iso_list
    fi
}

# uncompress cloud image
#
# @private
# @param string _filepath path to file to decompress
#
core_decompress(){
    local _filepath

    cmd_parse_args "$@"
    shift $?
    _filepath="${1}"

    if echo "${_filepath}" | grep "\.xz$" > /dev/null; then
        xz -d "${_filepath}"
    elif echo "${_filepath}" | grep "\.tar\.gz$" > /dev/null; then
        tar Szxf "${_filepath}" -C "$(dirname "${_filepath}")"
        rm -f "${_filepath}"
    elif echo "${_filepath}" | grep "\.gz$" > /dev/null; then
        gunzip "${_filepath}"
    fi
}

# 'vm img'
# list cloud images or get a new one
#
# @param string _url if specified, the url will be fetch'ed into $vm_dir/.img
#
core_img(){
    local _url _ds="default" _filename
    local _fetch_opts
    if ! which qemu-img > /dev/null; then
        util_err "Error: qemu-img is required to work with cloud images! Run 'pkg install qemu-tools'."
    fi

    while getopts 46d:u _opt ; do
        case $_opt in
            4) _fetch_opts="${_fetch_opts} -4" ;;
            6) _fetch_opts="${_fetch_opts} -6" ;;
            d) _ds=${OPTARG} ;;
            *) help_show "img" ;;
        esac
    done

    shift $((OPTIND - 1))
    _url=$1

    if [ -n "${_url}" ]; then
        datastore_get_img "${_ds}" || util_err "unable to locate path for datastore '${_ds}'"
        _filename=$(basename "${_url}")
        # converted from Fetch to Curl
	case "${_fetch_opts}" in
	    *"-4"*)
        	_curl_opts="-4"
        	;;
	    *"-6"*)
        	_curl_opts="-6"
        	;;
	    *)
        	_curl_opts=""
        	;;
	esac
	curl -L ${_curl_opts} -o "${VM_DS_PATH}/${_filename}" "${_url}" || \
	    util_err "failed to download cloud image"
	core_decompress "${VM_DS_PATH}/${_filename}"
    else
        datastore_img_list
    fi
}

# 'vm passthru'
# show a list of available passthrough devices
# and their device number
#
core_passthru(){
    local _dev _sbf _desc _ready
    local _format="%-12s %-12s %-8s %s\n"
    printf "${_format}" "DEVICE" "PCI ID" "READY" "DESCRIPTION"
    lspci -D | while read -r _sbf _desc; do
        _dev="${_sbf}"
        _ready="No"
        if [ -e "/sys/bus/pci/devices/${_dev}/driver" ]; then
            _driver=$(basename "$(readlink \
                "/sys/bus/pci/devices/${_dev}/driver" 2>/dev/null)")
        else
            _driver=""
        fi

        if [ "${_driver}" = "vfio-pci" ]; then
            _ready="Yes"
        fi
        printf "${_format}" \
            "${_dev}" \
            "${_sbf}" \
            "${_ready}" \
            "${_desc:--}"
    done
}

# 'vm get'
# get a core configuration setting
#
core_get(){
    local _var="$1"
    local _val _format="%-20s%s\n"
    local IFS=";"

    printf "${_format}" "SETTING" "VALUE"

    if [ "${_var}" = "all" ]; then

        for _var in ${VM_CONFIG_USER}; do
            config_core_get "_val" "${_var}"
            printf "${_format}" "${_var}" "${_val:--}"
        done
    else
        while [ -n "${_var}" ]; do
            if util_valid_config_setting "${_var}"; then
                config_core_get "_val" "${_var}"
                printf "${_format}" "${_var}" "${_val:--}"
            fi

            shift
            _var="$1"
        done
    fi
}

# 'vm set'
# set a core configuration setting
#
core_set(){
    local _pair="$1"
    local _key _val

    while [ -n "${_pair}" ]; do
        _key="${_pair%%=*}"
        _val="${_pair#*=}"

        if util_valid_config_setting "${_key}"; then
            config_core_set "${_key}" "${_val}"
        else
            util_err "invalid configuration setting - '${_key}'"
        fi

        shift
        _pair="$1"
    done
}
