#!/bin/sh
# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2016 Matt Churchyard <churchers@gmail.com>

CMD_VALID_LIST="init,switch,datastore,image,get,set,list,create,destroy,rename,install,start,stop,restart"
CMD_VALID_LIST="${CMD_VALID_LIST},add,reset,poweroff,startall,stopall,console,iso,img,configure,passthru,_run"
CMD_VALID_LIST="${CMD_VALID_LIST},info,clone,snapshot,rollback,migrate,version,usage,edit"
CMD_VALID_LIST="${CMD_VALID_LIST},suspend,suspendall,discard,help,tags"

# cmd: vm ...
#
# handle simple information commands that don't need any
# priviledged access or bhyve support
#
# @param string _cmd the command right after 'vm '
#
cmd_parse_info(){
    local _cmd

    # no arguments at all: fall through to cmd_parse, which prints usage
    [ -z "$1" ] && return 0

    cmd_find "_cmd" "$1" "${CMD_VALID_LIST}"

    # "vm <subcommand> -h" command also displays help about any subcommand
    case "$2" in
        -h|--help) help_show "${_cmd}" ;;
    esac

    case "${_cmd}" in
        version) util_version && exit ;;
        usage)   util_usage ;;
        # "vm help <subcommand>" displays help about any subcommand
        help)
            [ -z "$2" ] && help__help
            help_show "$2"
	    exit
	    ;;
    esac
}

# cmd: vm ...
#
# process the vm command line to see which function is requested
#
# @param string _cmd the command right after 'vm '
#
cmd_parse(){
    local _cmd

    # try to find a matching command
    cmd_find "_cmd" "$1" "${CMD_VALID_LIST}" || util_usage
    shift

    case "${_cmd}" in
        init)      util_setup
                   switch_init ;;
        switch)    cmd_parse_switch "$@" ;;
        datastore) cmd_parse_datastore "$@" ;;
        image)     cmd_parse_image "$@" ;;
        get)       core_get "$@" ;;
        set)       core_set "$@" ;;
        list)      core_list "$@" ;;
        create)    core_create "$@" ;;
        destroy)   core_destroy "$@" ;;
        discard)   core_discard "$@" ;;
        rename)    core_rename "$@" ;;
        install)   core_install "$@" ;;
        start)     core_start "$@" ;;
        stop)      core_stop "$@" ;;
        restart)   core_restart "$@" ;;
        suspend)   core_suspend "$@" ;;
        add)       core_add "$@" ;;
        reset)     core_reset "$@" ;;
        poweroff)  core_poweroff "$@" ;;
        startall)  core_startall ;;
        stopall)   core_stopall ;;
        suspendall) core_suspendall ;;
        console)   core_console "$@" ;;
        iso)       core_iso "$@" ;;
        img)       core_img "$@" ;;
        configure|edit) core_configure "$@" ;;
        passthru)  core_passthru ;;
        _run)      vm_run "$@" ;;
        info)      info_guest "$@" ;;
        clone)     zfs_clone "$@" ;;
        snapshot)  zfs_snapshot "$@" ;;
        rollback)  zfs_rollback "$@" ;;
        migrate)   migration_run "$@" ;;
        tags)      cmd_parse_tags "$@" ;;
        *)         util_err "unknown command '${_user_cmd}'. please run 'vm usage' or view the manpage for help" ;;
    esac
}

# cmd: vm tags ...
#
# parse tags command
cmd_parse_tags(){
    local _cmd

    [ -z "$1" ] && help_show "tags"

    # try to find a matching command
    cmd_find "_cmd" "$1" "add,remove,list,find,help" || help_show "tags"
    shift

    case "${_cmd}" in
        add)     tags_add "$@" ;;
        remove)  tags_remove "$@" ;;
        list)    tags_list "$@" ;;
        find)    tags_find "$@" ;;
        help)    help_show "tags" ;;
    esac
}

# cmd: vm switch ...
#
# parse switch command
# we've already shifted once, so $1 is the switch function
#
# @param string _cmd the command right after 'vm switch '
#
cmd_parse_switch(){
    local _cmd

    [ -z "$1" ] && help_show "switch"

    # try to find a matching command
    cmd_find "_cmd" "$1" "create,list,destroy,add,remove,vlan,nat,address,private,info" || help_show "switch"
    shift

    case "${_cmd}" in
        create)  switch_create "$@" ;;
        list)    switch_list ;;
        destroy) switch_remove "$@" ;;
        add)     switch_add_member "$@" ;;
        remove)  switch_remove_member "$@" ;;
        vlan)    switch_vlan "$@" ;;
        nat)     switch_nat "$@" ;;
        address) switch_address "$@" ;;
        private) switch_private "$@" ;;
        info)    info_switch "$@" ;;
        *)       util_err "unknown command '${_user_cmd}'. please run 'vm usage' or view the manpage for help" ;;
    esac
}

# cmd: vm datastore ...
#
# parse a datastore command
#
# @param string _cmd the command after 'vm datastore ...'
#
cmd_parse_datastore(){
    local _cmd

    [ -z "$1" ] && help_show "datastore"

    # try to find a matching command
    cmd_find "_cmd" "$1" "list,add,remove,iso,img" || help_show "datastore"
    shift

    case "${_cmd}" in
        list)   datastore_list ;;
        add)    datastore_add "$@" ;;
        remove) datastore_remove "$@" ;;
        iso)    datastore_iso "$@" ;;
        img)    datastore_img "$@" ;;
        *)      util_err "unknown command '${_user_cmd}'. please run 'vm usage' or view the manpage for help" ;;
    esac
}

# cmd 'vm image ...'
# parse the image command set
#
# @param string _cmd the command after 'vm image '
#
cmd_parse_image(){
    local _cmd

    [ -z "$1" ] && help_show "image"
    [ -z "${VM_ZFS}" ] && util_err "\$vm_dir must be a ZFS datastore to use these functions"

    # try to find a matching command
    cmd_find "_cmd" "$1" "list,create,provision,destroy" || help_show "image"
    shift

    case "${_cmd}" in
        list)      zfs_image_list ;;
        create)    zfs_image_create "$@" ;;
        provision) zfs_image_provision "$@" ;;
        destroy)   zfs_image_destroy "$@" ;;
        *)         util_err "unknown command '${_user_cmd}'. please run 'vm usage' or view the manpage for help" ;;
    esac
}

# many commands accept the same arguments (force being the obvious one)
# provide a function to parse these so we don't have to keep
# repeating the same getopt code. the return value here is the number
# of arguments the caller needs to shift.
#
# note that start/install/_run use -f for foreground mode
#
# @param _arglist[multiple] the callers $@
# @return number of arguments caller should shift over
#
cmd_parse_args(){
    local _opt _count

    # getopts never resets OPTIND by itself. Without this, any function
    # that runs getopts earlier in the same process (core_create,
    # core_iso, migration_run, ...) leaves OPTIND pointing past the end
    # of our argument list and "shift $?" below eats the real arguments.
    OPTIND=1

    while getopts fitv _opt; do
        case ${_opt} in
            f) VM_OPT_FORCE="1"
               VM_OPT_FOREGROUND="1" ;;
            i) VM_OPT_INTERACTIVE="1" ;;
            t) VM_OPT_TMUX="1" ;;
            v) VM_OPT_VERBOSE="1" ;;
        esac
    done

    [ -n "${VM_OPT_FOREGROUND}" ] && [ -n "${VM_OPT_INTERACTIVE}" ] && \
      util_err "foreground and interactive mode are mutually exclusive"

    return $((OPTIND - 1))
}

# try to match part of a command name against a list of valid commands
# if we find more than one match we return an error
# if we only get one match, return the full command name
#
# @param string _var variable to put full command name into
# @param string _user_cmd the value provided by the user
# @param string _valid comma-separated list of valid choices
# @return success if we find one match
#
cmd_find(){
    local _var="$1"
    local _user_cmd="$2"
    local _valid="$3"
    local _opt _choice _found=""
    local IFS=","

    [ -n "${_user_cmd}" ] || return 1

    for _opt in ${_valid}; do
        # exact match?
        if [ "${_user_cmd}" = "${_opt}" ]; then
            setvar "${_var}" "${_opt}"
            return 0
        fi

        if echo "${_opt}" | grep -iqs "^${_user_cmd}"; then
           [ -n "${_found}" ] && util_err "ambiguous command '${_user_cmd}'"

           _found=1
           _choice="${_opt}"
        fi
    done

    [ -z "${_found}" ] && return 1
    setvar "${_var}" "${_choice}"
}
