#!/bin/sh
# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2016 Matt Churchyard <churchers@gmail.com>
# SPDX-FileCopyrightText: 2026 Petr Derbyshev <drvpotr@gmail.com>
#
# Linux port of vm-bhyve's vxlan switch implementation.
#
# This file was still pure FreeBSD: it drove ifconfig(8) with vxlanid/
# vxlanlocal/vxlangroup/vxlandev/descr/group, route(8) with -iface, and
# md5(1) - none of which exist on Linux. Every vxlan operation therefore
# failed, even though vm-switch advertises vxlan as a supported type.
#
# The Linux equivalents used here:
#   ifconfig vxlanN create vxlanid.. -> ip link add .. type vxlan id ..
#   ifconfig bridge create           -> ip link add .. type bridge
#   ifconfig brX addm vxlanN         -> ip link set vxlanN master brX
#   route add -net M/32 -iface if    -> ip route add M/32 dev if
#   md5 -qs                          -> md5sum
#
# VXLAN also needs a destination UDP port. FreeBSD defaults to 4789 (the
# IANA-assigned port); the Linux kernel defaults to the older 8472 for
# historical reasons, so 4789 is requested explicitly to stay
# interoperable with FreeBSD hosts on the same segment.

VM_VXLAN_PORT="4789"

# create a vxlan switch
# we create a bridge and then add the vxlan interface to it
#
# @param string _name name of the switch
#
switch_vxlan_init(){
    local _name="$1"
    local _id _vlan _if _maddr _addr _local _mac _vxdev

    # see if the bridge already exists
    switch_standard_id "_id" "${_name}" && return 0

    # need a vlan id and interface
    config_core_get "_vlan" "vlan_${_name}"
    config_core_get "_if" "ports_${_name}"
    [ -z "${_vlan}" -o -z "${_if}" ] && return 1

    # get local address for this interface
    _local=$(ip -4 -o addr show dev "${_if}" 2>/dev/null | \
        awk '{print $4}' | cut -d/ -f1 | head -n 1)
    [ -z "${_local}" ] && \
        util_err "unable to find an IPv4 address on ${_if} for vxlan switch ${_name}"

    # come up with an ip address for multicast data
    switch_vxlan___multicast "_maddr" "${_name}"

    # create the vxlan interface
    _vxdev="vxlan${_vlan}"

    if ! ip link show dev "${_vxdev}" >/dev/null 2>&1; then
        ip link add name "${_vxdev}" type vxlan id "${_vlan}" \
            group "${_maddr}" local "${_local}" dev "${_if}" \
            dstport "${VM_VXLAN_PORT}" >/dev/null 2>&1
        [ $? -eq 0 ] || util_err "failed to create vxlan interface ${_vxdev} for switch ${_name}"

        ip link set dev "${_vxdev}" up >/dev/null 2>&1
    fi

    # create a bridge for this switch
    switch___bridge_name "_id" "${_name}"

    if ip link show dev "${_id}" >/dev/null 2>&1; then
        util_err "failed to create bridge interface for switch ${_name}: ${_id} already exists"
    fi

    ip link add name "${_id}" type bridge >/dev/null 2>&1
    [ $? -eq 0 ] || util_err "failed to create bridge interface for switch ${_name}"

    ip link set dev "${_id}" up >/dev/null 2>&1
    switch_set_viid "${_name}" "${_id}"

    # randomise mac (locally-administered unicast; see switch_standard_init)
    _mac=$(
        set -- $(od -An -N6 -tx1 /dev/urandom 2>/dev/null)
        [ $# -ge 6 ] && printf "%02x:%s:%s:%s:%s:%s" \
            $(( (0x$1 & 0xfe) | 0x02 )) "$2" "$3" "$4" "$5" "$6"
    )
    [ -n "${_mac}" ] && \
        ip link set dev "${_id}" address "${_mac}" >/dev/null 2>&1

    # bridge vxlan to our guest switch, and make sure traffic for the
    # multicast group leaves via the interface the user selected
    ip link set dev "${_vxdev}" master "${_id}" >/dev/null 2>&1
    ip route add "${_maddr}/32" dev "${_if}" >/dev/null 2>&1

    # custom address for bridge?
    config_core_get "_addr" "addr_${_name}"
    [ -n "${_addr}" ] && \
        ip addr add "${_addr}" dev "${_id}" >/dev/null 2>&1

    return 0
}

# show the configuration details for a vxlan switch
#
# @param string _name the switch name
# @param string _format output format
#
switch_vxlan_show(){
    local _name="$1"
    local _format="$2"
    local _id _vlan _port _addr _priv

    switch_standard_id "_id" "${_name}"
    config_core_get "_vlan" "vlan_${_name}"
    config_core_get "_port" "ports_${_name}"
    config_core_get "_addr" "addr_${_name}"
    config_core_get "_priv" "private_${_name}" "no"

    printf "${_format}" "${_name}" "vxlan" "${_id:--}" "${_addr:--}" "${_priv}" "n/a" "${_vlan:--}" "${_port:--}"
}

# create a vxlan switch
#
switch_vxlan_create(){

    # we must have an interface and vlan to use
    [ -z "${_if}" -o -z "${_vlan}" ] && util_err "vxlan switches must be created with an interface and vlan id specified"

    # store configuration
    config_core_set "switch_list" "${_switch}" "1"
    config_core_set "type_${_switch}" "vxlan"
    config_core_set "vlan_${_switch}" "${_vlan}"
    config_core_set "ports_${_switch}" "${_if}"

    [ -n "${_addr}" ] && config_core_set "addr_${_switch}" "${_addr}"
    [ -n "${_priv}" ] && config_core_set "private_${_switch}" "${_priv}"

    config_core_load
    switch_vxlan_init "${_switch}"
}

# destroy a vxlan switch
#
# @param string _switch the switch to remove
#
switch_vxlan_remove(){
    local _switch="$1"
    local _id _vlan _maddr _if

    # try to get guest bridge and vxlan id
    switch_standard_id "_id" "${_switch}"
    [ $? -eq 0 ] || return 1

    config_core_get "_vlan" "vlan_${_switch}"
    [ -z "${_vlan}" ] && return 1

    config_core_get "_if" "ports_${_switch}"

    # get the multicast address we used for this switch
    # and try to remove any route we may have added
    switch_vxlan___multicast "_maddr" "${_switch}"
    ip route del "${_maddr}/32" dev "${_if}" >/dev/null 2>&1

    # destroy the guest bridge
    ip link set dev "${_id}" down >/dev/null 2>&1
    ip link delete dev "${_id}" type bridge >/dev/null 2>&1
    [ $? -eq 0 ] || return 1

    # destroy the vxlan
    ip link set dev "vxlan${_vlan}" down >/dev/null 2>&1
    ip link delete dev "vxlan${_vlan}" type vxlan >/dev/null 2>&1
}

# add a new interface to this switch
# we only allow a single physical interface for
# vxlan switches. this must be set at creation time
# so this just reports an error
#
# @param string _switch name of the vxlan switch
# @param string _if the interface to add
#
switch_vxlan_add_member(){
    util_err "vxlan interface must be configured at creation time"
}

# remove an interface from a switch
# we don't support this here
#
# @param string _switch name of the switch
# @param string _if the interface to remove
#
switch_vxlan_remove_member(){
    util_err "vxlan interface must be configured at creation time"
}

# set vlan id
#
# @param string _switch name of switch
# @param int _vlan vlan id to set
#
switch_vxlan_vlan(){
    util_err "vxlan id can only be set at creation time"
}

# get the multicast address for a vxlan switch
#
# Linux: md5(1) is a FreeBSD base utility; the coreutils equivalent is
# md5sum, which reads stdin and appends a filename field. The resulting
# 239.x.y.z address is the same either way, so FreeBSD and Linux hosts
# sharing a switch name still land on the same group.
#
# @param string _var variable to put address into
# @param string _switch the switch name
#
switch_vxlan___multicast(){
    local _var="$1"
    local _switch="$2"
    local _hash _l_addr _octet _pos

    # come up with an ip address for multicast data
    _hash=$(printf '%s' "${_switch}" | md5sum | awk '{print $1}')
    _l_addr="239"

    for _pos in 1-2 3-4 5-6; do
        _octet=$(printf ".%d" "0x$(echo "${_hash}" | cut -c ${_pos})")
        _l_addr="${_l_addr}${_octet}"
    done

    setvar "${_var}" "${_l_addr}"
}
