#!/bin/sh
# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2016 Matt Churchyard <churchers@gmail.com>
# SPDX-FileCopyrightText: 2026 Petr Derbyshev <drvpotr@gmail.com>

# switch libraries
#
# VALE (netmap) and netgraph are FreeBSD kernel-specific technologies
# with no Linux equivalent, so those switch types aren't offered in
# this port - there's nothing to source for them, and sourcing a
# nonexistent file here would break every 'vm' invocation, not just
# switch commands. 'standard' (linux bridge) and 'vxlan' (also a real
# Linux feature) still need their own lib files - just not shown here.
#
. "${LIB}/vm-switch-manual"
. "${LIB}/vm-switch-standard"
. "${LIB}/vm-switch-vxlan"

# create switches from rc list on init
# this should run once per boot to make sure switches from the
# configuration file have bridge interfaces. If any new switches are
# created, the create function takes care of setting them up
#
switch_init(){
    local _switchlist _switch _type

    config_core_get "_switchlist" "switch_list"

    if [ -n "${_switchlist}" ]; then
        for _switch in ${_switchlist}; do
            # get the switch type
            config_core_get "_type" "type_${_switch}"

            case "${_type}" in
                vxlan)    switch_vxlan_init "${_switch}" ;;
                manual)   switch_manual_init "${_switch}" ;;
                vale|netgraph)
                    # non-fatal: this loop covers every switch on the
                    # host, one unsupported entry (e.g. a leftover from
                    # a migrated FreeBSD config) shouldn't stop the
                    # rest from coming up
                    util_warn "switch ${_switch} is type '${_type}', which isn't supported on Linux - skipping"
                    ;;
                *)        switch_standard_init "${_switch}" ;;
            esac
        done
    fi
}

# list switches configured
#
switch_list(){
    local _switchlist _switch _type
    local _id _format="%s^%s^%s^%s^%s^%s^%s^%s\n"

    config_core_get "_switchlist" "switch_list"

    {
        printf "${_format}" "NAME" "TYPE" "IFACE" "ADDRESS" "PRIVATE" "MTU" "VLAN" "PORTS"

        if [ -n "${_switchlist}" ]; then
            for _switch in ${_switchlist}; do
                # get the switch type
                config_core_get "_type" "type_${_switch}"

                case "${_type}" in
                    vxlan)    switch_vxlan_show "${_switch}" "${_format}" ;;
                    manual)   switch_manual_show "${_switch}" "${_format}" ;;
                    vale|netgraph)
                        # same reasoning as switch_init - flag it in
                        # the table instead of aborting the whole listing
                        printf "${_format}" "${_switch}" "${_type}" "unsupported-on-linux" "-" "-" "-" "-" "-"
                        ;;
                    *)        switch_standard_show "${_switch}" "${_format}" ;;
                esac
            done
        fi
    } | column -ts^
}

# create a new virtual switch
#
# @param string _switch name of the switch to create
#
switch_create(){
    local _switch
    local _type="standard"
    local _list _curr _vlan _if _bridge _addr _mtu _priv

    # process options
    while getopts t:i:n:b:a:m:p _opt; do
        case ${_opt} in
            t) _type="${OPTARG}" ;;
            i) _if="${OPTARG}" ;;
            n) _vlan="${OPTARG}" ;;
            b) _bridge="${OPTARG}" ;;
            a) _addr="${OPTARG}" ;;
            m) _mtu="${OPTARG}" ;;
            p) _priv="yes" ;;
            *) util_usage ;;
        esac
    done

    shift $((OPTIND - 1))
    _switch="$1"

    # check for a valid switch name
    util_check_name "${_switch}" || util_err "invalid switch name - '${_switch}'"

    # make sure it's not an existing name
    config_core_get "_list" "switch_list"

    for _curr in ${_list}; do
        [ "${_switch}" = "${_curr}" ] && util_err "switch ${_switch} already exists"
    done

    # check vlan number
    if [ -n "${_vlan}" ]; then
        echo "${_vlan}" | egrep -qs '^[0-9]{1,4}$'
        [ $? -eq 0 ] || util_err "invalid vlan number"
        [ ${_vlan} -ge 4095 ] && util_err "invalid vlan number"
    fi

    # check address
    if [ -n "${_addr}" ]; then
        util_validate_cidr "${_addr}"
        [ $? -eq 0 ] || util_err "address must be supplied in CIDR notation (e.g. 192.0.2.1/24, 3fff_1/64)"
    fi

    # check mtu
    if [ -n "${_mtu}" ]; then
        echo "${_mtu}" | egrep -qs '^[0-9]{3,4}$'
        [ $? -eq 0 ] || util_err "invalid mtu"
        [ ${_mtu} -gt 9000 ] && util_err "invalid mtu"
    fi

    # check switch type
    case "${_type}" in
        standard) switch_standard_create ;;
        manual)   switch_manual_create ;;
        vxlan)    switch_vxlan_create ;;
        vale|netgraph)
            util_err "switch type '${_type}' is not supported on Linux"
            ;;
        *)        util_err "invalid switch type - '${_type}'" ;;
    esac
}

# destroy a switch
# remove from configuration and unload any interfaces we created
#
# @param string _switch name of the switch to remove
#
switch_remove(){
    local _switch="$1"
    local _type

    [ -z "${_switch}" ] && util_usage

    # get the type of switch
    config_core_get "_type" "type_${_switch}"

    case "${_type}" in
        standard) switch_standard_remove "${_switch}" ;;
        manual)   switch_manual_remove "${_switch}" ;;
        vxlan)    switch_vxlan_remove "${_switch}" ;;
        vale|netgraph)
            util_err "switch type '${_type}' is not supported on Linux"
            ;;
        *)        util_err "unable to remove switch of unknown type" ;;
    esac

    # remove all configuration if there's no error
    if [ $? -eq 0 ]; then
        config_core_remove "switch_list" "${_switch}"
        config_core_remove "ports_${_switch} vlan_${_switch} nat_${_switch} type_${_switch}"
        config_core_remove "addr_${_switch} addr6_${_switch} private_${_switch} mtu_${_switch}"
    else
        util_err "failed to remove virtual switch"
    fi

    # make sure the exit status indicates success,
    # even if config_core_remove did not
    return 0
}

# add a new interface to a switch
#
# @param string _switch name of the switch
# @param string _if the interface to add
#
switch_add_member(){
    local _switch="$1"
    local _if="$2"
    local _type

    [ -z "${_switch}" -o -z "${_if}" ] && util_usage

    # get the type of switch
    config_core_get "_type" "type_${_switch}"

    case "${_type}" in
        standard) switch_standard_add_member "${_switch}" "${_if}" ;;
        manual)   switch_manual_add_member "${_switch}" "${_if}" ;;
        vxlan)    switch_vxlan_add_member "${_switch}" "${_if}" ;;
        vale|netgraph)
            util_err "switch type '${_type}' is not supported on Linux"
            ;;
        *)        util_err "unable to configure switch of unknown type" ;;
    esac
}

# remove a member interface from a virtual switch
#
# @param string _switch name of the switch
# @param string _if the interface to remove
#
switch_remove_member(){
    local _switch="$1"
    local _if="$2"
    local _type

    [ -z "${_switch}" -o -z "${_if}" ] && util_usage

    # get the type of switch
    config_core_get "_type" "type_${_switch}"

    case "${_type}" in
        standard) switch_standard_remove_member "${_switch}" "${_if}" ;;
        manual)   switch_manual_remove_member "${_switch}" "${_if}" ;;
        vxlan)    switch_vxlan_remove_member "${_switch}" "${_if}" ;;
        vale|netgraph)
            util_err "switch type '${_type}' is not supported on Linux"
            ;;
        *)        util_err "unable to configure switch of unknown type" ;;
    esac
}

# change the vlan number on a virtual switch
#
# @param string _switch name of the switch
# @param int _vlan the vlan number (0 to turn vlan off)
#
switch_vlan(){
    local _switch="$1"
    local _vlan="$2"
    local _id _type

    [ -z "${_switch}" -o -z "${_vlan}" ] && util_usage

    switch_id "_id" "${_switch}"
    switch_type "_type" "${_switch}"
    [ -z "${_id}" ] && util_err "unable to locate specified virtual switch"

    echo "${_vlan}" | egrep -qs '^[0-9]{1,4}$'
    [ $? -eq 0 ] || util_err "invalid vlan number"
    [ ${_vlan} -ge 4095 ] && util_err "invalid vlan number"

    case "${_type}" in
        standard) switch_standard_vlan "${_switch}" "${_vlan}" ;;
        manual)   switch_manual_vlan "${_switch}" "${_vlan}" ;;
        vxlan)    switch_vxlan_vlan "${_switch}" "${_vlan}" ;;
        vale|netgraph)
            util_err "switch type '${_type}' is not supported on Linux"
            ;;
        *)        util_err "unable to configure switch of unknown type" ;;
    esac
}

# enable or diable private flag on a switch
# note that we don't update existing interfaces; this
# makes things easy for us and any guests booted after
# will get the new setting
#
# @param string _switch the switch to update
# @param string _priv on,yes|off,no
#
switch_private(){
    local _switch="$1"
    local _priv="$2"
    local _type

    # try to get switch type
    [ -z "${_switch}" -o -z "${_priv}" ] && util_usage
    switch_type "_type" "${_switch}" || util_err "specified switch does not appear to be valid"

    case "${_type}" in
        standard|manual|vxlan)
            if util_yesno "${_priv}"; then
                config_core_set "private_${_switch}" "yes"
            else
                config_core_set "private_${_switch}" "no"
            fi
            ;;
        vale|netgraph)
            util_err "switch type '${_type}' is not supported on Linux"
            ;;
        *)
            util_err "unable to configure switch of unknown type"
            ;;
    esac
}

# enable or disable nat functionality on a virtual switch
#
# @param string _switch name of the switch
# @param string _nat on|off
#
switch_nat(){
    util_warn "internal nat support is currently disabled"
    util_warn "please add an address to the virtual switch and configure your firewall for NAT manually"
}

# set or remove ip address from a virtual switch
#
# @param string _switch name of the switch
# @param string _addr the ip address to add (or "none" to remove
#
switch_address(){
    local _switch="$1"
    local _addr="$2"
    local _delete="$3"
    local _id _type

    [ -z "${_switch}" ] && util_usage

    switch_id "_id" "${_switch}"
    switch_type "_type" "${_switch}"
    [ -z "${_id}" ] && util_err "unable to locate specified virtual switch"

    # check address
    if [ -n "${_addr}" ] && [ "${_addr}" != "none" ]; then
        util_validate_cidr "${_addr}"
        [ $? -eq 0 ] || util_err "address must be supplied in cidr notation (e.g. 192.0.2.1/24, 3fff_1/64)"
    fi

    case "${_type}" in
        standard) switch_standard_address "${_switch}" "${_addr}" "${_delete}";;
        manual)   ;&
        vxlan)    util_err "feature not currently supported on switches of this type" ;;
        vale|netgraph)
            util_err "switch type '${_type}' is not supported on Linux"
            ;;
        *)        util_err "unable to configure switch of unknown type" ;;
    esac
}

# return the type for a switch
#
# @param string _var variable to put type into
# @param string _switch the switch name
#
switch_type(){
    local _var="$1"
    local _switch="$2"

    [ -z "${_switch}" ] && return 1
    config_core_get "${_var}" "type_${_switch}" "standard"
}

# check if a switch is configured for private members
#
# @param string _switch switch name
# @return succes (0) if it's private
#
switch_is_private(){
    local _switch="$1"
    local _priv

    config_core_get "_priv" "private_${_switch}"
    util_yesno "${_priv}"
}

# get the bridge id for a virtual switch
#
# @param string _var variable to put name into
# @param string _switch the name of the switch
#
switch_id(){
    local _var="$1"
    local _switch="$2"
    local _type

    [ -z "${_switch}" ] && return 1

    # get switch type
    config_core_get "_type" "type_${_switch}"

    case "${_type}" in
        manual)   switch_manual_id "${_var}" "${_switch}" ;;
        vale|netgraph)
            util_err "switch type '${_type}' is not supported on Linux"
            ;;
        *)        switch_standard_id "${_var}" "${_switch}" ;;
    esac
}

# get a virt interface id for a port/switch
#
# Linux: FreeBSD hashes the switch name into a short group name because
# ifconfig group names share the same length/character limits as
# interface names. Linux's ifalias (sysfs) is a free-text field with no
# such constraint, so we can just tag it with the switch name directly -
# no hashing needed, and it's human-readable in `ip link show` output.
#
# @param string _var variable name to put result into
# @param string _switch switch name to get id for
#
switch___viid(){
    setvar "$1" "vm-switch/${2}"
}

# retrieve interface name, given a switch name
# we convert to viid then look for the interface carrying that alias
#
# @param string _var variable to put interface name into
# @param string _switch the switch name
#
switch_find(){
    local _var="$1"
    local _switch="$2"
    local _viid _f _alias

    switch___viid "_viid" "${_switch}"

    for _f in /sys/class/net/*/ifalias; do
        [ -r "${_f}" ] || continue
        _alias=$(cat "${_f}" 2>/dev/null)

        if [ "${_alias}" = "${_viid}" ]; then
            setvar "${_var}" "$(basename "$(dirname "${_f}")")"
            return 0
        fi
    done

    return 1
}

# mark an interface with a unique viid
#
# @parem string _switch switch name
# @param string _iface interface to mark
#
switch_set_viid(){
    local _switch="$1"
    local _iface="$2"
    local _viid

    switch___viid "_viid" "${_switch}"
    ip link set dev "${_iface}" alias "${_viid}" >/dev/null 2>&1
}

# create a network interface for a guest
# relies heavily on variables set in the main vm_run function
#
# @modifies _func _devices
#
switch_provision(){
    local _switch _mac _type

    config_get "_switch" "network${_num}_switch"
    config_get "_mac" "network${_num}_mac"

    # set a static mac if we don't have one
    [ -z "${_mac}" ] && vm_generate_static_mac

    switch_type "_type" "${_switch}"

    case "${_type}" in
        standard) ;&
        manual)   ;&
        vxlan)    switch_standard_provision ;;
        vale|netgraph)
            util_warn "switch type '${_type}' is not supported on Linux - interface ${_num} not configured"
            ;;
        *)        util_warn "unable to configure interface ${_num}" ;;
    esac
}
