#!/bin/sh
# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2025 Koichiro Iwao (metalefty) <meta@FreeBSD.org>

# Assign tags to specified virtual machine
# @param string _name target virtual machine name
# @param string _tags ...
#
tags_add(){
    local _name _tags _tag

    _name="$1"
    shift
    _tags="$@"

    [ -z "${_name}" ] && help_show "tags"
    [ -z "${_tags}" ] && help_show "tags"

    for _tag in ${_tags}; do
        util_check_name "${_tag}" || util_err "invalid tag name - '${_tag}'"
    done

    datastore_get_guest "${_name}" || util_err "${_name} doesn't appear to be a valid virtual machine"

    config_file_append "${VM_DS_PATH}/${_name}/${_name}.conf" "tags" "${_tags}"
}

# Remove tags from specified virtual machine
# @param string _name target virtual machine name
# @param string _tags ...
#
tags_remove(){
    local _name _tags

    _name="$1"
    shift
    _tags="$@"

    [ -z "${_name}" ] && help_show "tags"
    [ -z "${_tags}" ] && help_show "tags"

    datastore_get_guest "${_name}" || util_err "${_name} doesn't appear to be a valid virtual machine"

    config_file_remove_value "${VM_DS_PATH}/${_name}/${_name}.conf" "tags" "${_tags}"
}

# List tags assigned to target
# @param string _name
#
tags_list(){
    local _name
    local _tags

    _name="$1"

    [ -z "${_name}" ] && help_show "tags"

    datastore_get_guest "${_name}" || util_err "${_name} doesn't appear to be a valid virtual machine"

    config_load_file_value "_tags" "${VM_DS_PATH}/${_name}/${_name}.conf" "tags"

    echo "${_tags}"
}

# Shows a list of VMs that have specified tag
# @param string tag
#
tags_find(){
    local _tag _result

    _result=""
    _tag="$1"
    shift

    [ -z "${_tag}" ] && help_show "tags"

    for _ds in ${VM_DATASTORE_LIST}; do
        datastore_get "${_ds}" || continue

    exec 9<<EOF
$(ls -1 "${VM_DS_PATH}" 2>/dev/null)
EOF

        while read _name; do
            [ ! -e "${VM_DS_PATH}/${_name}/${_name}.conf" ] && continue
            config_load_file_value "_tags" "${VM_DS_PATH}/${_name}/${_name}.conf" "tags"
	    printf '%s\n' "${_tags}" | grep -q -w "${_tag}"
            if [ $? -eq 0 ]; then
                _result="${_result} ${_name}"
            fi
        done <&9
    done
    echo $_result
}

